---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.k3ao.devinyoung.io
spec:
  group: k3ao.devinyoung.io
  names:
    kind: Agent
    listKind: AgentList
    plural: agents
    singular: agent
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Agent is the Schema for the agents API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AgentSpec defines the desired state of Agent
            properties:
              address:
                description: IP address/hostname of k3s agent host
                type: string
              port:
                description: SSH port of k3s agent host
                format: int32
                type: integer
              sshKeySecretName:
                description: Name of the secret that holds the SSH credentials to
                  the host
                type: string
            required:
            - address
            - sshKeySecretName
            type: object
          status:
            description: AgentStatus defines the observed state of Agent
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
